version: "3"

services:
  database:
    env_file: 
      - envs/database/development.env
    image: postgres:12.2-alpine
    container_name: database.development.knufesta2019
    volumes:
      - database.development.knufesta2019:/var/lib/postgresql/data
    networks:
      - development.knufesta2019

  logic:
    env_file:
      - envs/logic/development.env
    container_name: logic.development.knufesta2019
    build:
      context: ./
      dockerfile: docker/development/Dockerfile
    volumes:
      - "./:/logic"
    ports:
      - "8000:8000"
    networks:
      - development.knufesta2019

volumes:
  database.development.knufesta2019:
    external: true


networks:
  development.knufesta2019:
    external: true
