version: "3.7"

services:
  db:
    env_file: 
      - db/.env
    image: postgres:12.2-alpine
    container_name: knufestival2019-db
    volumes:
      - ./db/volume:/var/lib/postgresql/data

  web:
    env_file:
      - web/config/credentials/.dev
    container_name: knufestival2019-web
    build:
      context: ./web
      dockerfile: ./project_install/dev/Dockerfile
    volumes:
      - "./web:/web"
    ports:
      - "8000:8000"
