version: "3.7"

services:
  db:
    env_file: 
      - env/develop/db.env
    image: postgres:12.2-alpine
    container_name: knufestival2019-db
    volumes:
      - ./db/volume:/var/lib/postgresql/data

  web:
    env_file:
      - env/develop/web.env
    container_name: knufestival2019-web
    build:
      context: ./web
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - "./web:/web"
    ports:
      - "8000:8000"
