version: "3.8"

services:
  database:
    env_file: 
      - ../../../database/env/.production/.env
    image: postgres:12.2-alpine
    container_name: database.production.knufesta2019
    volumes:
      - database.production.knufesta2019:/var/lib/postgresql/data
    networks:
      - production.knufesta2019

  logic:
    env_file:
      - ../../../logic/env/.production/.env
    image: lunacircle4/logic.knufesta2019:1.0.0
    build:
      context: ../../../logic
      dockerfile: docker/production/Dockerfile
    container_name: logic.production.knufesta2019
    volumes:
      - ../../../webserver/static:/logic/static  
      - ../../../webserver/media:/logic/media
    networks:
      - production.knufesta2019
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"

  webserver:
    image: nginx:1.19.1 # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    container_name: webserver.production.knufesta2019
    volumes:
      - ../../../webserver/env/.production/nginx.conf:/etc/nginx/nginx.conf
      - ../../../webserver/env/.production/1.0.0.conf:/etc/nginx/conf.d/nginx.conf
      - ../../../webserver/static:/knufesta2019/static  
      - ../../../webserver/media:/knufesta2019/media
    depends_on: # 서비스 간의 종속성 표현
      - logic
    networks:
      - production.knufesta2019
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"

volumes:
  database.production.knufesta2019:
    external: true

networks:
  production.knufesta2019:
    external: true
