version: "3.7"

services:
  db:
    env_file: 
      - ../env/develop/db.env
    image: postgres:12.2-alpine
    container_name: knufestival2019-db
    volumes:
      - ./db/volume:/var/lib/postgresql/data

  web:
    env_file:
      - ../../envs/soho_1.0.0/web.env
    container_name: knufestival2019-web
    image: lunacircle4/knufestival2019:1.0.0
    volumes:
      - "./web:/web"
    ports:
      - "8000:8000"
