apiVersion: apps/v1
kind: Deployment
metadata:
  name: knufestival2019-nfs-server
  namespace: production
spec:
  selector:
    matchLabels:
      role: knufestival2019-nfs-server
  template:
    metadata:
      labels:
        role: knufestival2019-nfs-server
    spec:
      containers:
      - name: knufestival2019-nfs-server
        image: itsthenetwork/nfs-server-alpine:11-arm
        env:
        - name: SHARED_DIRECTORY
        - value: "/exports"
      value: "Warm greetings to"
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: knufestival2019-nfs-client
  namespace: production
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    role: knufestival2019-nfs-server
