apiVersion: apps/v1
kind: Deployment
metadata:
  name: knu-festival-was
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knu-festival-was
  template:
    metadata:
      labels:
        app: knu-festival-was
    spec:
      containers:
      - name: web
        image: lunacircle4/knufestival2019:1.0.0
        envFrom:
        - secretRef:
            name: knufestival2019-was-env
---
apiVersion: batch/v1
kind: Job
metadata:
  name: knu-festival-migrator
  namespace: production
spec:
  template:
    spec:
      containers:
      - name: knu-festival-migrator
        image: lunacircle4/knufestival2019:1.0.0
        command: ["python3 manage.py migrate --settings=config.environments.production"]
        envFrom:
        - secretRef:
            name: knufestival2019-was-env
      restartPolicy: Never
  backoffLimit: 4
