apiVersion: apps/v1
kind: Deployment
metadata:
  name: knu-festival-was
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knu-festival-was
  template:
    metadata:
      labels:
        app: knu-festival-was
    spec:
      containers:
      - name: web
        image: lunacircle4/knufestival2019:1.0.0
        envFrom:
        - secretRef:
            name: knufestival2019-was-env
---
apiVersion: v1
kind: EphemeralContainers
metadata:
  name: knu-festival-was-migrate
  namespace: production
ephemeralContainers:
  - image: lunacircle4/knufestival2019:1.0.0
    envFrom:
    - secretRef:
        name: knufestival2019-was-env
    command: [
      "python3 manage.py migrate --settings=config.environments.production"
    ]
    imagePullPolicy: "IfNotPresent"
    name: "knu-festival-was-migrate"
