apiVersion: batch/v1
kind: Job
metadata:
  name: production-migrator
  namespace: knufesta2019
spec:
  template:
    spec:
      containers:
      - name: production-migrator
        image: lunacircle4/was.knufesta2019:${TAG}
        command: ["/bin/sh"]
        args: ["-c", "python3 manage.py migrate --settings=config.environments.production;"]
        envFrom:
        - secretRef:
            name: was-production-env
      restartPolicy: Never
  backoffLimit: 4
