apiVersion: v1
kind: Service
metadata:
  name: knufestival2019-web-service
  namespace: production
spec:
  ports:
    - name: knufestival2019-web-port
      port: 80
      targetPort: 80
  selector:
    app: knufestival2019-web
  type: NodePort
