apiVersion: apps/v1
kind: Deployment
metadata:
  name: knu-festival

spec:
  replicas: 2
  selector:
    matchLabels:
      app: knu-festival-web

  template:
    metadata:
      labels:
        app: knu-festival-web

    spec:
      containers:
      - name: knu-festival-web
        image: nginx
        ports:
          - containerPort: 80