apiVersion: apps/v1
kind: Deployment
metadata:
  name: knu-festival

spec:
  replicas: 2
  selector:
    matchLabels:
      app: knu-festival-was

  template:
    metadata:
      labels:
        app: knu-festival-was

    spec:
      containers:
      - name: web
        image: knu-festival:1.0.0
